DROP TABLE IF EXISTS mangas;

CREATE TABLE mangas (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    author VARCHAR(250) NOT NULL,
    number INTEGER NOT NULL,
    gender VARCHAR(250) NOT NULL,
    editor VARCHAR(250) NOT NULL
);